package com.louis.icemango.dao;

import com.louis.icemango.model.SysConfig;
import java.util.List;

public interface SysConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbggenerated Fri Sep 17 16:33:55 CST 2021
     */
    int insert(SysConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbggenerated Fri Sep 17 16:33:55 CST 2021
     */
    List<SysConfig> selectAll();
}