package com.louis.icemango.dao;

import com.louis.icemango.model.SysDict;
import java.util.List;

public interface SysDictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict
     *
     * @mbggenerated Fri Sep 17 16:33:55 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict
     *
     * @mbggenerated Fri Sep 17 16:33:55 CST 2021
     */
    int insert(SysDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict
     *
     * @mbggenerated Fri Sep 17 16:33:55 CST 2021
     */
    SysDict selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict
     *
     * @mbggenerated Fri Sep 17 16:33:55 CST 2021
     */
    List<SysDict> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict
     *
     * @mbggenerated Fri Sep 17 16:33:55 CST 2021
     */
    int updateByPrimaryKey(SysDict record);
}