package com.louis.icemango.dao;

import com.louis.icemango.model.SysLoginLog;
import java.util.List;

public interface SysLoginLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_login_log
     *
     * @mbggenerated Fri Sep 17 16:33:55 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_login_log
     *
     * @mbggenerated Fri Sep 17 16:33:55 CST 2021
     */
    int insert(SysLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_login_log
     *
     * @mbggenerated Fri Sep 17 16:33:55 CST 2021
     */
    SysLoginLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_login_log
     *
     * @mbggenerated Fri Sep 17 16:33:55 CST 2021
     */
    List<SysLoginLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_login_log
     *
     * @mbggenerated Fri Sep 17 16:33:55 CST 2021
     */
    int updateByPrimaryKey(SysLoginLog record);
}