package com.louis.icemango.dao;

import com.louis.icemango.model.SysRoleMenu;
import java.util.List;

public interface SysRoleMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu
     *
     * @mbggenerated Fri Sep 17 16:33:55 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu
     *
     * @mbggenerated Fri Sep 17 16:33:55 CST 2021
     */
    int insert(SysRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu
     *
     * @mbggenerated Fri Sep 17 16:33:55 CST 2021
     */
    SysRoleMenu selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu
     *
     * @mbggenerated Fri Sep 17 16:33:55 CST 2021
     */
    List<SysRoleMenu> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu
     *
     * @mbggenerated Fri Sep 17 16:33:55 CST 2021
     */
    int updateByPrimaryKey(SysRoleMenu record);
}